# Create a GitHub action to email a report from a file at 6 a.m. daily

name: Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  email_report:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: 'Daily Report'
          body: 'Please find the daily report attached.'
          to: ${{ secrets.EMAIL }}
          attachments: 'report.txt'